import React from "react";

export function SkillGapPage({ skillGaps, darkMode }) {
  return (
    <div className="space-y-8">
      <div className={`rounded-3xl p-6 sm:p-8 shadow-sm border transition-all ${
        darkMode ? "bg-slate-900 border-slate-800 text-white" : "bg-white border-slate-200 text-slate-900"
      }`}>
        <h2 className="text-2xl font-bold">AI Skill Gap Analysis & Learning Roadmaps</h2>
        <p className={`text-sm mt-1 ${darkMode ? "text-slate-400" : "text-slate-600"}`}>
          Targeted recommendations generated by the Skill Gap Agent to upgrade your eligibility for top target internships.
        </p>
      </div>

      <div className="space-y-6">
        {skillGaps?.map((gap, idx) => (
          <div
            key={idx}
            className={`rounded-3xl shadow-sm border p-6 sm:p-8 space-y-6 transition-all ${
              darkMode ? "bg-slate-900 border-slate-800 text-white" : "bg-white border-slate-200 text-slate-900"
            }`}
          >
            <div className={`flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b pb-5 ${
              darkMode ? "border-slate-800" : "border-slate-100"
            }`}>
              <div>
                <span className="text-xs font-bold text-amber-400 bg-amber-950/60 px-2.5 py-1 rounded-md border border-amber-800/40">
                  Target Role #{idx + 1}
                </span>
                <h3 className="text-xl font-bold mt-2">{gap.job_title}</h3>
                <p className={`text-sm font-semibold ${darkMode ? "text-slate-400" : "text-slate-600"}`}>{gap.company}</p>
              </div>
              <div className="text-right">
                <span className="text-2xl font-black text-purple-500 block">{gap.match_percentage}%</span>
                <span className={`text-xs font-bold ${darkMode ? "text-slate-500" : "text-slate-400"}`}>Current Compatibility</span>
              </div>
            </div>

            {/* Recommendation Alert */}
            <div className={`p-5 rounded-2xl border ${
              darkMode ? "bg-amber-950/30 border-amber-800/40 text-amber-300" : "bg-gradient-to-r from-amber-50 to-orange-50 border-amber-200 text-amber-900"
            }`}>
              <h4 className="text-sm font-bold flex items-center gap-2">
                <span>💡</span> AI Skill Gap Recommendation
              </h4>
              <p className="text-sm mt-2 leading-relaxed opacity-90">{gap.recommendation}</p>
            </div>

            {/* Actionable Learning Path */}
            {gap.learning_path?.length > 0 && (
              <div>
                <h4 className={`text-xs font-bold uppercase tracking-wider mb-3 ${darkMode ? "text-slate-400" : "text-slate-700"}`}>
                  Actionable Recommended Steps
                </h4>
                <div className="space-y-2">
                  {gap.learning_path.map((step, sIdx) => (
                    <div
                      key={sIdx}
                      className={`flex items-start gap-3 p-3.5 rounded-2xl border text-xs sm:text-sm ${
                        darkMode ? "bg-slate-850 border-slate-800 text-slate-300" : "bg-slate-50 border-slate-100 text-slate-700"
                      }`}
                    >
                      <span className="bg-blue-600 text-white font-bold text-xs rounded-full w-5 h-5 flex items-center justify-center flex-shrink-0 mt-0.5 shadow-sm">
                        {sIdx + 1}
                      </span>
                      <span>{step}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
